name: Deployment to K8S

on:
  push:
    branches: ["master"]

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest

    steps:
      - name: Set up buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.CONTAINER_REGISTRY_URL }}
          username: ${{ secrets.CONTAINER_REGISTRY_USER }}
          password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.CONTAINER_REGISTRY_URL }}/calendar-team/calendar-frontend:${{ github.sha }}

  deploy:
    name: Deploy to K8S
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Set the Kubernetes context
        uses: azure/k8s-set-context@v4
        with:
          method: service-account
          k8s-url: ${{ secrets.K8S_URL }}
          k8s-secret: ${{ secrets.K8S_SECRET }}

      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Create calendar-frontend namespace
        uses: azure/k8s-deploy@v5
        with:
          manifests: |
            k8s/namespace.yaml

      - name: Create container-registry secret
        uses: azure/k8s-create-secret@v5
        with:
          namespace: calendar-frontend
          secret-name: ghcr-secret
          container-registry-url: ${{ secrets.CONTAINER_REGISTRY_URL }}
          container-registry-username: ${{ secrets.CONTAINER_REGISTRY_USER }}
          container-registry-password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}

      - name: Create nextauth secret key
        uses: azure/k8s-create-secret@v5
        with:
          namespace: calendar-frontend
          secret-name: nextauth-secret
          secret-type: generic
          string-data: ${{ secrets.NEXTAUTH_SECRET }}

      - name: Deploy to the K8S cluster
        uses: azure/k8s-deploy@v5
        with:
          namespace: calendar-frontend
          manifests: |
            k8s/deployment.yaml
            k8s/service.yaml
            k8s/ingress.yaml
          images: |
            ${{ secrets.CONTAINER_REGISTRY_URL }}/calendar-team/calendar-frontend:${{ github.sha }}
